name: CI/CD Pipeline

env:
    DOCKER_REPO: boonfu/frontend

on:
    push:
        branches: [dev, main]

jobs:
    build-or-promote:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.DOCKER_REPO }}
                  labels: |
                      maintainer=BoonFu
                      project.environment=${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
                      type=sha,prefix=prod-,enable=${{ github.ref == 'refs/heads/main' }}
                      type=raw,value=staging,enable=${{ github.ref == 'refs/heads/dev' }}
                      type=sha,prefix=staging-,enable=${{ github.ref == 'refs/heads/dev' }}
                      type=semver,pattern={{version}}
                      type=ref,event=pr,enable=${{ github.event_name == 'pull_request' }}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and Push Dev
              if: github.ref == 'refs/heads/dev'
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  no-cache: true
                  build-args: |
                      VITE_ENV=dev
                      VITE_FRONTEND_URL=https://boonfu.site/
                      VITE_BACKEND_URL=https://api.boonfu.site/

            - name: Promote Dev to Main
              if: github.ref == 'refs/heads/main'
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  no-cache: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      VITE_ENV=prod
                      VITE_NODE_ENV=prod
                      VITE_FRONTEND_URL=https://boonfu.com/
                      VITE_BACKEND_URL=https://api.boonfu.com/

    deploy:
        needs: build-or-promote
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Trigger Coolify (Main/Prod)
              if: github.ref == 'refs/heads/main'
              run: |
                  curl --request GET '${{ secrets.COOLIFY_PROD_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_PROD_TOKEN }}'
            - name: Trigger Coolify (Dev)
              if: github.ref == 'refs/heads/dev'
              run: |
                  curl --request GET '${{ secrets.COOLIFY_DEV_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_DEV_TOKEN }}'
