name: ci

on:
  push:
    branches:
      - main
      - devops

jobs:
  login-to-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  check_container_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Container Runtime
        run: |
          docker info | grep Container
  install_continerd:
    runs-on: ubuntu-latest
    needs: login-to-docker
    steps:
      - uses: actions/checkout@v3
      - name: Run Bash Commands
        run: |
          curl -fsSL https://github.com/docker/buildx/releases/download/v0.8.2/buildx-installer | bash
          docker buildx create --name my-builder --driver docker-containerd
          docker buildx use my-builder
  verify_container_runtime:
    needs: install_continerd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Container Runtime
        run: |
          docker info | grep Container
  build:
    needs: install_continerd
    runs-on: ubuntu-latest
    steps:
        - name: Build and push Docker Image
          uses: docker/build-push-action@v6
          with:
            platforms: linux/amd64,linux/arm64/v8
            push: true
            target: deploy
            tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
            build-args: |
              VITE_CLOUDINARY_API_KEY=${{secrets.VITE_CLOUDINARY_API_KEY}}
              VITE_CLOUDINARY_SECRET=${{secrets.VITE_CLOUDINARY_SECRET}}
              VITE_CLOUD_NAME=${{secrets.VITE_CLOUD_NAME}}
              VITE_UPLOAD_PRESET=${{secrets.VITE_UPLOAD_PRESET}}
              PLATFORM=linux/amd64,linux/arm64/v8
              
              
